### ISSUE TITLE
undefined is not an object (evaluating 'u.current[h].scrollPos=window.scrollY') error fix

### ISSUE THREAD

**Issue by jieyou** [AlexSapoznikov/react-next-keep-alive#6]
Hello, Thank you for creating such a lib, so that Nextjs can easily obtain the ability to keep-alive the page like Vue.

But when using it in the production environment, we found that such a js exception was often thrown.

```
undefined is not an object (evaluating 'u.current[h].scrollPos=window.scrollY')
```

This is because lib provides the `keepAliveDropCache` method that can be called anywhere. We can drop the cache of a certain page at any time. After the drop, if we call 

```
keepAliveCache.current[name].scrollPos = window.scrollY;
```

again, it will report this error.

It is also very simple to solve this problem. Only need to judge whether the current `keepAliveCache.current[name]` exists when executing it. Only need to modify
https://github.com/AlexSapoznikov/react-next-keep-alive/blob/master/src/provider.tsx#L95
from

```
if (isKeptAlive) {
```

to

```
if (isKeptAlive && keepAliveCache.current[name]) {
```

Wondering if you could fix it and make a new minor iteration?

**Comment by AlexSapoznikov** [comment]
@jieyou Hi. Please see if this is fixed now with 1.0.16
